spring.application.name=mtgdeck-app

# Configuración del servidor
server.port=8080

# Configuración de base de datos PostgreSQL (Supabase)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate ddl-auto (crea y actualiza las tablas automáticamente en base a tus entidades)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
